POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "name": "any name",
    "email": "any_email@email.com",
    "password": "12345678",
    "phoneNumber": "11999999999"
}

###
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "any_email@email.com",
    "password": "12345678"
}